# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 18255b96f59d3ea5c68412877085c89555dcc7c6c1af7675043e18249733dd0805910fde6cf821ea7e68c0d2cc103898e1f20321d1a063ced85c61fc132241b8

test:
  secret_key_base: 1578be1167bf0cab4a328fde91b93ab6284cb0c1b41862f971acd8486d4ae8cbc82c7fbb3a30b949e2153ae342a629d10f177700cb25376a1f6b8fa1650e02d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
